name: cryptotax_helper
description: "CryptoTax Helper is your ultimate financial companion, designed to simplify cryptocurrency tax tracking and portfolio management with a sleek, intuitive dark-themed interface."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  fl_chart: 0.68.0
  intl: 0.20.2
  firebase_core: ^4.0.0
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
